#!/bin/bash
# @COPYRIGHT@

WIKITESTS="/usr/share/nlw/wikitests"

echo SETTING TIME
source $WIKITESTS/set-time

echo set-default-account Socialtext
sudo -u www-data st-admin set-default-account --account  Socialtext

echo INSTALLING and ENABLING  all plugins
sudo st-appliance-install-plugin dashboard people socialcalc
sudo -u www-data st-admin enable-plugin --account Socialtext --plugin dashboard
sudo -u www-data st-admin enable-plugin --account Socialtext --plugin people
sudo -u www-data st-admin enable-plugin --account Socialtext --plugin socialcalc

echo INSTALLING wikitest_files
if [ ! -e /opt/wikitest_files ]; then
    sudo mkdir /opt/wikitest_files
fi
sudo unzip $WIKITESTS/wikitestfiles.zip -d /opt/wikitest_files/

if [ -e /var/www/socialtext/data/test-data ]; then
    echo "DELETING old test-data workspace"
    sudo -u www-data /usr/bin/st-admin delete-workspace --w test-data  --no-export
fi
echo "IMPORTING  test-data  WORKSPACE"
sudo -u www-data /usr/bin/st-admin import-workspace --tarball $WIKITESTS/test-data.tar.gz

if [ -e /var/www/socialtext/data/wikitests ]; then
    echo DELETING old wikitests workspace
    sudo -u www-data /usr/bin/st-admin delete-workspace --w wikitests --no-export
fi
echo "IMPORTING wikitests WORKSPACE"
sudo -u www-data /usr/bin/st-admin import-workspace --tarball $WIKITESTS/wikitests.1.tar.gz

echo "SETTING user accounts to Socialtext"
sudo -u www-data st-admin set-user-account --e wikitester@ken.socialtext.net --account Socialtext
sudo -u www-data st-admin set-user-account --e devnull1@socialtext.com --account Socialtext

echo "GRANTING Accounts and System admin to devnull1"
sudo -u www-data /usr/bin/st-admin give-system-admin --e devnull1@socialtext.com
sudo -u www-data /usr/bin/st-admin give-accounts-admin --e devnull1@socialtext.com

echo "INSTALLING slapd"
sudo apt-get install slapd

sudo /usr/bin/st-socialcalc enable

# Make www-data own /etc/socialtext/ files so st-bootstrap-openldap will
# succeed from wikitests.
sudo chown -R www-data:www-data /etc/socialtext/
echo "DONE"
