#!/usr/bin/perl
# @COPYRIGHT@

use strict;
use warnings;
use Sys::Hostname;

if ( Sys::Hostname::hostname =~ /^www2?\.socialtext\.net$/ ) {
   print "Migrating account features.\n";
   exit 0;
}

print "Skipping Migration, assuming this was done by hand.\n";
exit 1;
