#!/bin/bash

MIGDIR=`dirname $0`
DB_USER=`st-config echo db_user`
DB_SCHEMA=`st-config echo db_schema_name`

# Make sure all the tables exist.
for table in event event_id_seq person tag tag_id_seq person_watched_people__person tag_people__person_tags; do
    RESULT=`sudo -u postgres psql $DB_SCHEMA -c "SELECT relname FROM pg_class WHERE relname = '$table'" | grep '1 row'`

  if [ -n "$RESULT" ]; then
      FOUND=$(($FOUND + 1))
  fi
done

if [ $FOUND == 7 ]; then
  echo "Socialtext People tables are installed, Migration Success."
  exit 0
fi

if [ $FOUND == 0 ]; then
  echo "Socialtext People tables are not installed, Total migration failure."
  exit 1
fi

echo "Something is very wrong, please contact Socialtext at support@socialtext.com ASAP!"
exit -1
