#!/bin/sh

# Strip off the path info to find the name of this script
SCRIPT_NAME=`basename $0`

# Use the refactored column adding code
MIG_DIR=`dirname $0`/..

$MIG_DIR/add-column/$SCRIPT_NAME Workspace customjs_name text "''"

if [ "$SCRIPT_NAME" = "migration" ]; then
    $MIG_DIR/add-column/_set_not_null Workspace customjs_name "''"
fi

