#!/usr/bin/env perl -w
#@COPYRIGHT@
use strict;
use Sys::Hostname;
my $host = hostname;

#Touch and chmod the logs
grant_write_permissions_to_local_logs($host);
#Create the account data
#--------------------------------------------#
my $exec = './st-create-account-data';
my $strGrowth = './st-qa-growth-report-add-members';

unless (is_dev_env($host)) {
   $exec = 'sudo -u www-data ' . $exec;   
   $strGrowth ='sudo -u www-data ' . $exec;
}

my $results = `$strGrowth`;
my $str = `$exec`;
$str=~/Account ID: (\d*)\n/;
my $account_id = $1;
print "ID Is $account_id, host is $host\n";


#Process the logs
#----------------------------------------------#
if (!(is_dev_env($host))) {
`sudo /usr/bin/st-reports-consume-nlw-log /var/log/nlw.log 2>&1`;

}



#Delete data from DB
#----------------------------------------------#
my $userid = `whoami`;
chomp($userid);
print "User ID is '$userid' \n\n\n\n";
my $u = '';
my $db = 'NLW_reports';
if (is_dev_env($host)) {
    $db.="_".$userid;
} else {
    $u = '-U nlw ';
}
my $delete_1 = 'psql ' . $u . $db . ' -c "delete from actions_by_user where account_id =' . $account_id . '; "';
`$delete_1`;
my $delete_2 = 'psql ' . $u . $db . ' -c "delete from nlw_log_actions where account_id =' . $account_id . '; "';
`$delete_2`;



#Part II of the Workspace Reports
#-----------------------------------------------#
my $populate_db = './st-qa-growth-report-populate-db';
unless (is_dev_env($host)) {
   $populate_db ='sudo -u www-data ' . $populate_db;
}
$results = `$populate_db`;


#Import Data into DB
#-----------------------------------------------#
if (is_dev_env($host)) {
   `./st-consume-stub-reports`;
} else {
   `sudo /usr/bin/st-reports-import-nlw-data test_nlw.log`;
   `sudo /usr/bin/st-reports-consume-access-log test_access.log`;
   `sudo /usr/bin/st-reports-consume-nlw-log test_nlw.log`;
}

#---------------------------------------------------------------#
# End Main Routine Subroutines Follow                           #
#---------------------------------------------------------------#
#
sub status_wait {
    my ($count, $reason) = @_;
    print "Waiting $count minutes for $reason\n";
    local $| = 1;
    my $idx; my $jdx;
    for ($idx=0;$idx<$count;$idx++) {
        print "Waiting $idx ";
        for ($jdx=0;$jdx<10;$jdx++) {
            sleep(10);
            print ".";
        }
        print "\n";
    }
}


sub is_dev_env {
    my $host = shift;
    if ($host=~/talc/ || $host=~/topaz/) {
        return 1; 
    } else {
        return 0;
    }
}

sub grant_write_permissions_to_local_logs {  
    my $host = shift;
    `sudo chmod 777 ./`;
    `touch test_access.log`;
    `touch test_nlw.log`;
    `sudo chmod 666 test_access.log`;
    `sudo chmod 666 test_nlw.log`;
    if (is_dev_env($host)) {
        `sudo rm ~/.nlw/cache/logreader/test*`;
    } else {
        `sudo rm /var/cache/socialtext/logreader/test*`;
    }    
}
